### ISSUE TITLE
Feature Request: suspend user instead of unenroll when enrollment condition no longer valid

### ISSUE THREAD

**Issue by on8pz** [ndunand/moodle-enrol_attributes#25]
Feature request: Add an option to suspend a user instead of unenrolling it after the enrollment condition is no longer valid.
We are happily using your plugin in our educational environment but we need to keep all info of students that unsubscribed from a course for historical purposes. When a student is unenrolled by the plugin, his or her information is hidden from the course.
It would be more convenient if the student is suspended instead of unenrolled so that all information stays visible.

Right now I have solved this by modifying <sitedir>/enrol/attributes/lib.php  on line 296 :

Original code:
`$enrol_attributes_instance->unenrol_user($unenrol_attributes_record, (int)$userid);`

My code:
`$enrol_attributes_instance->update_user_enrol($unenrol_attributes_record, (int)$userid, ENROL_USER_SUSPENDED);`

Would it be possible to add an option to the plugin settings to give site admins this choice so that I don't have to do this again with every update ?

Thanks!
Hans

**Comment by ndunand** [comment]
Hi @on8pz Hans,

Thanks for the suggestion. I've implemented this as it really sounds useful. Here's how it works for now (unreleased, see commit 7dd6e61):
 - site admin can choose default behaviour between : do nothing, unenrol, suspend;
 - teacher can choose behaviour for each instance, same options;
 - existing options ('unenrol' checked/unchecked) stay the same but now display as selector instead of checkbox.

Let me know what you think,
Nicolas

**Comment by on8pz** [comment]
Unfortunately cannot test it right now due to some problems with our test environment, but it sounds great the way you describe it !
Thanks!

**Comment by ndunand** [comment]
Okay. This new feature is now available in the latest release.
