### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by luisdev** [ndunand/moodle-enrol_attributes#49]
The Moodle forum discussion https://moodle.org/mod/forum/discuss.php?d=344132#p1388090 says that:

"A plugin (in my case [Enrol by User Profile Fields](https://moodle.org/plugins/enrol_attributes)) that run an infinite loop after login caused the long loading time."

That is a very old post, but has this "infinite loop" problem been investigated and fixed?

**Comment by NicoAlexH** [comment]
This might have been related to this issue https://github.com/ndunand/moodle-enrol_attributes/issues/7. 
I haven't been able to reproduce this behaviour and it has not been reported since then. As the code has been improved since 2016 (caching has been implemented among other things), I think we can consider it as fixed. 
Feel free to create a new issue if it happens again.
